/*
 * Copyright (c) 2026 Jamie Malcolm
 * Released under the BSD 3-Clause License. See LICENSE for terms.
 */
package logratio.api;

import logratio.core.PairAligner;
import logratio.core.PairEstimator;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * Frozen coefficients for {@link AutomaticRegistrationSelector}.
 *
 * <p>GENERATED FILE. Rewritten by {@code logratio.FullSelectorTraining} from the full candidate sweep:
 * 96 log-ratio recipes over support, band, filter and mask, and 16 area-correlation candidates
 * over band and filter.
 * Do not hand-edit: the numbers below are the output of leave-one-source-series-out training
 * and carry no meaning apart from that fit. Retraining is the only supported way to change them.
 */
public final class AutomaticRegistrationSelectorModel {

    /** Number of standardised evidence columns the frozen fit expects. */
    public static final int FEATURE_COUNT = readAtRuntime(48);

    /** Either {@code image_type_rule}, {@code linear_gain}, or {@code untrained}. */
    public static final String MODEL_KIND = readAtRuntime("image_type_rule");

    /** Provenance of the fit, printed in the settings report. */
    public static final String TRAINED_ON = readAtRuntime("full_selector_sweep_v1: 80 controlled recordings, 20 leave-one-source-series-out folds; held-out mean median 0.020258 px against a category recommendation of 0.025545 px");

    /** Minimum predicted gain, in pixels, before an override is allowed. */
    public static final double CONFIDENCE_THRESHOLD = readAtRuntime(0.005);

    /**
     * Identity, and the only reason it exists is to stop javac copying the value into its callers.
     *
     * <p>A {@code static final} field initialised with a literal is a compile-time constant, and
     * javac copies its value into every class that reads it instead of compiling a field read.
     * This file is regenerated by training, so a class that is not recompiled afterwards would
     * keep answering with the previous model's values, silently — which has happened twice, once
     * scoring a sealed test set against the wrong model. Routing the value through a method makes
     * the initialiser a method call rather than a constant expression, so stale readers read the
     * current value. See {@code docs/performance_optimisation_findings.md}.
     *
     * <p>Emitted by {@code logratio.FullSelectorTraining}. A regeneration that writes bare literals
     * reopens the trap.
     */
    private static int readAtRuntime(int value) {
        return value;
    }

    /** See {@link #readAtRuntime(int)}. */
    private static double readAtRuntime(double value) {
        return value;
    }

    /** See {@link #readAtRuntime(int)}. */
    private static String readAtRuntime(String value) {
        return value;
    }

    public static final double[] FEATURE_MEAN = {
            0.26525034369378264, 0.35580808096462124, 0.37878226525181236, 1.7091882143062123,
            0.07716125588197373, 0.0187887319605275, 2.5590509992639943, 48.03994171748874,
            0.05438950664375878, 0.1555454343064075, 0.029658012761930003, 0.09446968146424375,
            0.03570815258345126, 0.11394167738646248, 0.7984765371881251, 0.7698742778808125,
            0.760688096500975, 0.7718807469623998, 1.731550216805412, 2.51991482896785,
            4.345391582687376, 0.4058718768294611, 0.22561712747549292, 0.8687552494772,
            1.9211035036728876, 2.927548705002187, 12.230504712257872, 0.2573415368618375,
            1.56000506233375, 0.004156238942484999, 0.8171657380896378, 0.8831210729028998,
            0.2, 0.2, 0.2, 0.2,
            0.2, 0.25, 0.25, 0.25,
            0.25, 0.25, 0.3, 0.45,
            0.0, 1.0, 0.0, 0.0
    };

    public static final double[] FEATURE_SCALE = {
            0.16941641371713936, 0.18764410354203584, 0.1619908205521054, 2.2941820532622663,
            0.07281560179960994, 0.013426906144392256, 4.272401078796081, 101.51277560508068,
            0.02735143892754771, 0.062296585764784154, 0.016364232948695455, 0.04510550338980435,
            0.016663156851066032, 0.055904231126087674, 0.112330977803736, 0.16878396353464797,
            0.1740095935975624, 1.184094003450402, 2.3616906366644366, 3.6887025720990825,
            4.358973335374299, 0.31358091647600433, 0.12321976264597939, 1.9232913802680613,
            3.750923045554166, 5.7100944599891035, 10.661581369953518, 0.1618886161756518,
            0.02363809604925261, 4.758454072781098E-4, 0.024036503182836105, 0.02150650321413865,
            0.3999999999999999, 0.39999999999999925, 0.39999999999999947, 0.40000000000000013,
            0.3999999999999997, 0.4330127018922193, 0.4330127018922193, 0.4330127018922193,
            0.4330127018922193, 0.4330127018922193, 0.45825756949558394, 0.4974937185533099,
            0.0, 0.0, 0.0, 0.0
    };

    /**
     * The declared image type each candidate is allowed to serve. A recipe safe for one image
     * type is never offered to another, which is where the first attempt at this selector
     * went wrong: a filter that helps brightfield destroys sparse low-light.
     */
    static final String[] CANDIDATE_IMAGE_TYPE = {
            "BRIGHTFIELD_DIC",
            "FIDUCIAL_STATIC"
    };

    /**
     * Which estimator each candidate uses. The axis beside the four settings dimensions:
     * {@code LOG_RATIO_FIT} is the engine this plugin is named for, {@code AREA_CORRELATION}
     * is normalised cross-correlation, and the settings below are inert under the latter.
     */
    static final String[] CANDIDATE_ESTIMATOR = {
            "AREA_CORRELATION_NEWTON",
            "AREA_CORRELATION_NEWTON"
    };

    static final String[] CANDIDATE_SUPPORT = {
            "ALL",
            "ALL"
    };

    static final String[] CANDIDATE_BAND = {
            "FULL",
            "FULL"
    };

    static final String[] CANDIDATE_FILTER = {
            "GAUSSIAN_0_7",
            "GAUSSIAN_0_7"
    };

    static final String[] CANDIDATE_MASK = {
            "NONE",
            "NONE"
    };

    /** Mean measured gain over the category recommendation on that image type. */
    static final double[] CANDIDATE_TRAINING_GAIN = {
            0.015279125, 0.011154749999999998
    };

    /** One-versus-rest gain regressions; row per candidate, column per feature. */
    static final double[] INTERCEPT = {};

    static final double[][] WEIGHTS = {
    };

    private AutomaticRegistrationSelectorModel() {
    }

    /** The retained candidate recipes, in the frozen model's order. */
    public static List<RegistrationRecipe> candidates() {
        List<RegistrationRecipe> out = new ArrayList<>();
        for (int i = 0; i < CANDIDATE_SUPPORT.length; i++) {
            out.add(RegistrationRecipe.swept(
                    PairEstimator.Kind.valueOf(CANDIDATE_ESTIMATOR[i]),
                    PairAligner.PixelSupport.valueOf(CANDIDATE_SUPPORT[i]),
                    RegistrationRecipe.Band.valueOf(CANDIDATE_BAND[i]),
                    Preprocessing.valueOf(CANDIDATE_FILTER[i]),
                    RegistrationRecipe.Mask.valueOf(CANDIDATE_MASK[i])));
        }
        return out;
    }

    /** The declared image type each candidate serves, aligned with candidates(). */
    public static List<ImageType> candidateImageTypes() {
        List<ImageType> out = new ArrayList<>();
        for (String name : CANDIDATE_IMAGE_TYPE) out.add(ImageType.valueOf(name));
        return out;
    }

    /**
     * Predicted gain over the category recommendation for every retained candidate. Candidates
     * that do not serve the declared image type score negative infinity and can never be chosen.
     */
    public static double[] predictGains(double[] standardised, ImageType imageType) {
        int count = CANDIDATE_SUPPORT.length;
        double[] out = new double[count];
        Arrays.fill(out, Double.NEGATIVE_INFINITY);
        if (count == 0) return out;
        for (int i = 0; i < count; i++) {
            if (imageType == null || !CANDIDATE_IMAGE_TYPE[i].equals(imageType.name())) continue;
            if ("image_type_rule".equals(MODEL_KIND)) {
                out[i] = CANDIDATE_TRAINING_GAIN[i];
                continue;
            }
            double value = INTERCEPT[i];
            double[] weights = WEIGHTS[i];
            for (int j = 0; j < weights.length; j++) value += weights[j] * standardised[j];
            out[i] = value;
        }
        return out;
    }
}
