"""Gain-invariant, robust registration of microscopy time series."""

__version__ = "0.3.0"

from .batch import BatchItem, BatchResult, register_batch
from .diagnostics import ChannelQuality, WARN_BELOW, correlation, frame_correlation, localisability, rank_channels
from .core import (
    AlignerOptions,
    LogPlane,
    Margin,
    PairFit,
    PairInfluence,
    PairResult,
    PairUncertainty,
    RegistrationOptions,
    RegistrationResult,
    RotationEvent,
    RotationEventResult,
    valid_margin,
    warp_plane,
)
from .io import read_tiff, register_file, write_tiff
from .longitudinal import LongitudinalDiagnostics
from .parameters import LogRatioParameters, RegistrationRecipe, recommendation
from .registration import (
    AutomaticSelection,
    BackendFallbackWarning,
    LogRatioResult,
    apply_transforms,
    estimate,
    infer_axes,
    register,
)
from .types import (
    Estimator,
    ImageType,
    Interpolation,
    MotionType,
    PixelSelectionStrategy,
    PixelSupport,
    Preprocessing,
    Reference,
    Recipe,
    ReconciliationWeighting,
    RotationEventStatus,
    RotationMode,
    RepairReason,
    RobustNorm,
    SelectionMode,
    Status,
    Transform,
)
from . import context
from .accepted_longitudinal import register_accepted

__all__ = [
    "register_accepted",
    "AlignerOptions",
    "AutomaticSelection",
    "BackendFallbackWarning",
    "BatchItem",
    "BatchResult",
    "ChannelQuality",
    "Estimator",
    "ImageType",
    "Interpolation",
    "LogPlane",
    "LogRatioParameters",
    "LogRatioResult",
    "LongitudinalDiagnostics",
    "Margin",
    "MotionType",
    "PairFit",
    "PairInfluence",
    "PairResult",
    "PairUncertainty",
    "PixelSelectionStrategy",
    "PixelSupport",
    "Preprocessing",
    "Reference",
    "Recipe",
    "ReconciliationWeighting",
    "RotationEventStatus",
    "RotationMode",
    "RegistrationOptions",
    "RegistrationRecipe",
    "RegistrationResult",
    "RotationEvent",
    "RotationEventResult",
    "RepairReason",
    "RobustNorm",
    "SelectionMode",
    "Status",
    "Transform",
    "WARN_BELOW",
    "__version__",
    "apply_transforms",
    "correlation",
    "estimate",
    "frame_correlation",
    "infer_axes",
    "localisability",
    "read_tiff",
    "recommendation",
    "register",
    "register_batch",
    "register_file",
    "rank_channels",
    "valid_margin",
    "warp_plane",
    "write_tiff",
    "context",
]
